actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations:
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: slack Approval
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Launch Task
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Action Required
    sysId: 931647e3250a4c588915dced21ceb34d
    task: APPROVAL-NOTIF-SLACK
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables:
    - name: task_status
      value: ${ops_status}
    - name: job_name
      value: ${ops_task_name}:${ops_task_id}
    - name: job_type
      value: ${ops_task_type}
    - name: invoked_by
      value: ${ops_workflow_name}
    - name: exec_user
      value: ${ops_execution_user}
    - name: desc
      value: ${ops_description}
    - name: msg
      value: Approve to process and publish the Data
    variablesUnresolved: false
    vertexSelection: false
    vertices: []
    virtualResource: null
    virtualResourceVar: null
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Launch Task
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: Action Required
    sysId: de45565b45584b7bbf98becfe8a8eda0
    task: Approval Notification to Teams
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables:
    - name: task_status
      value: ${ops_status}
    - name: job_name
      value: ${ops_task_name}
    - name: job_type
      value: ${ops_task_type}
    - name: invoked_by
      value: ${ops_workflow_name}
    - name: exec_user
      value: ${ops_execution_user}
    - name: desc
      value: ${ops_description}
    variablesUnresolved: false
    vertexSelection: false
    vertices: []
    virtualResource: null
    virtualResourceVar: null
avgRunTime: 473
avgRunTimeDisplay: 7 Minutes 53 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_manual
firstRun: 2023-06-06 12:32:35 +0200
holdResources: false
lastRun: 2023-07-27 14:49:33 +0200
lastRunTime: 82
lastRunTimeDisplay: 1 Minute 22 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 3126
maxRunTimeDisplay: 52 Minutes 6 Seconds
minRunTime: 12
minRunTimeDisplay: 12 Seconds
name: WMROTT-Approval-To-Continue-Workflow
notes: []
opswiseGroups:
- App1
overrideInstanceWait: 'No'
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 7
runTime: 3314
simulation: false
startHeld: false
startHeldReason: null
summary: Approve to Continue Workflow after forced stop
sysId: 1c426b7a0ce244048abd9694fa95cf6b
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskManual
userEstimatedDuration: null
variables: []
version: 2
virtualResources: []
