actions:
  abortActions: []
  emailNotifications: []
  setVariableActions:
  - description: null
    exitCodes: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    status: Success
    sysId: 7337f9b09c4347c389ccd89c6b30771c
    variableName: input_csv_files
    variableScope: Top Level Parent
    variableValue: ${ops_trigger_files}
  snmpNotifications: []
  systemOperations: []
agent: Kubernetes
agentCluster: null
agentClusterVar: null
agentVar: null
authenticatePeer: false
avgRunTime: 41
avgRunTimeDisplay: 41 Seconds
broadcastCluster: null
broadcastClusterVar: null
cpDuration: null
cpDurationUnit: Minutes
credentials: Kubernetes-ravi
credentialsVar: null
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_ftp_file_monitor
firstRun: 2023-09-26 16:18:44 +0200
ftpFmtype: Exist
holdResources: false
jobcard: null
lastRun: 2024-11-20 11:46:46 +0100
lastRunTime: 2
lastRunTimeDisplay: 2 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
listOptions: null
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 151
maxRunTimeDisplay: 2 Minutes 31 Seconds
minFileScale: KB
minFileSize: null
minRunTime: 2
minRunTimeDisplay: 2 Seconds
name: GET-MATCHING-FILE-LIST
notes: []
opswiseGroups: []
outputFailureOnly: false
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: STDOUT
overrideInstanceWait: 'No'
pollInterval: 10
pollMaximum: 20
remoteCredVar: null
remoteCredentials: Amsterdam-Ravi
remoteFilename: /home/ravi/input_file/INP_*${_date("MMddyyyy")}.dat
remoteServer: 172.31.13.232
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 7
runTime: 289
servertype: SFTP
simulation: false
stableSeconds: 5
startHeld: false
startHeldReason: null
summary: null
sysId: 1fee676c918f4ede9cf737007c475bde
timeZonePref: -- System Default --
transferMode: Passive
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFtpFileMonitor
useRegex: false
userEstimatedDuration: null
variables: []
verifyHostName: false
version: 5
virtualResources: []
wait: true
waitForOutput: true
