actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: ULM - SAP
agentCluster: SAP-Linux-agent
agentClusterVar: null
agentVar: null
broadcastCluster: null
broadcastClusterVar: null
chainDesc: null
chainId: null
commandGroup: Display
commandOptions: null
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
dataSource: null
defFile: null
definitionOrModel: USAP Definition File
definitionOrModelJobVar: SAP Model Job
dispAbapName: null
dispSapEventId: null
dispSapEventParm: null
dispVariant: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
emailNotification: null
enforceVariables: false
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_sap
firstRun: ''
holdResources: false
immediate: false
infoPackage: null
infoPackageJobName: null
infoSource: null
jobClass: null
jobId: null
jobLog: false
jobLogChild: null
jobName: FINALIZE-SALES-ORDER-DELIVERY
jobStatus: null
jobSteps: []
lastRun: ''
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logId: null
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxChildDepth: null
name: Demo-SAP-DISPLAY-1
notes: []
opswiseGroups:
- CHNG12121
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: OUTERR
outputType: STDOUT
overrideInstanceWait: 'No'
pcRestart: false
printAppLog: false
printAppRc: false
purge: false
purgeChild: null
repositoryOrFilesys: Script
requestId: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 0
runTime: 0
runtimeDir: null
sapCmProfileId: null
sapCmProfileType: null
sapCmXmlFile: null
sapCommandMask: null
sapConnection: null
sapConnectionVar: ${SAP_Hoffenheim_001}
sapCred: null
sapCredVar: ${sap_credential}
sapDispConfirmEvents: false
sapDispEventSelectState: New
sapDisplayCommand: Select
sapEventId: null
sapEventParm: null
sapFromDate: null
sapLang: null
sapPrinterName: null
sapToDate: null
sapView: Legacy View
script: null
simulation: false
sourceSystem: null
spoolListRecipient: null
spoollist: false
spoollistChild: null
start: false
startHeld: true
startHeldReason: null
stepNum: null
summary: Display SAP Job name and Job ID
sysId: e28072ac636e446ea205801261dea49b
targetJobName: null
targetServer: null
targetVariantName: null
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskSap
useAppRc: false
userEstimatedDuration: null
variables: []
version: 10
virtualResources: []
wait: false
waitChild: null
waitForOutput: false
