actions:
  abortActions: []
  emailNotifications:
  - attachFile: false
    attachStdError: false
    attachStdOut: false
    bcc: null
    body: "Hello. \n\nThis is notify that Job:${ops_task_name} running late , Following\
      \ are the details of the job\n\nAlert generated on: ${_date('yyyy-MM-dd')} at\
      \ ${_date('HH:mm:ss')} in time zone: ${ops_task_time_zone}\n\nTask Type: ${ops_task_type}\n\
      \nTask name: ${ops_task_name}\n\nWorkflow to which the task belongs (if it exists):\
      \ ${ops_workflow_name}\n\nTop-level parent workflow: ${ops_top_level_workflow_name}\n\
      \nTask Launched at ${ops_launch_time}\n\nTask Started at  ${ops_start_time}\n\
      \nTask Ended at    ${ops_end_time}\n\nStatus: ${ops_status}\n\nStatus Description:\
      \ ${ops_status_description}\n\nExit Code: ${ops_exit_code}\n\n************************************\n\
      \nHere is the Standard Output (if available):\n${_output('STDOUT')}\n\nHere\
      \ is the Standard Error (if available):\n${_output('STDERR')}\n\n************************************\n\
      \nUniversal Controller URL: ${UAC_Controller_URL}\n\n\nRegards,\nStonebranch\
      \ Operations"
    cc: null
    description: null
    emailConnection: email
    emailTemplate: UAC - Alert Template for Task Actions
    emailTemplateVar: null
    exitCodes: null
    fileName: ''
    fileNumLines: 100
    fileScanText: ''
    fileStartLine: 1
    listReportFormat: PDF
    notifyOnEarlyFinish: false
    notifyOnLateFinish: true
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    replyTo: null
    report: null
    reportVar: null
    status: ''
    stderrNumLines: 100
    stderrScanText: ''
    stderrStartLine: 1
    stdoutNumLines: 100
    stdoutScanText: ''
    stdoutStartLine: 1
    subject: 'ALERT: UAC Environment: "${ops_system_identifier}" Task: "${ops_task_name}"
      Status: ${ops_status} Time email sent: ${_date} - Running Late'
    sysId: 0e98bcc4c50d43d0bec5328282864956
    to: holger.justkowiak@stonebranch.com
  setVariableActions:
  - description: sap_ext_file_name
    exitCodes: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    status: Success
    sysId: 65676208d71749f6adf45d1546364cb9
    variableDescription: sap_ext_file_name
    variableName: sap_ext_file_name
    variableScope: Top Level Parent
    variableValue: C:\Users\ravi\sap_fico\superstore_central.csv
  snmpNotifications: []
  systemOperations:
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Cancel
    execCriteria: Oldest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: null
    execWorkflowName: null
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: true
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Launch Task
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: null
    sysId: a0d82f63b2854beda2c73060c18ced4e
    task: Create SNOW Incident
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables:
    - name: sib_failed_task_name
      value: ${ops_task_name}
    - name: sib_task_output
      value: 'ALERT: UAC Environment: "${ops_system_identifier}" Task: "${ops_task_name}"
        Status: ${ops_status} Time email sent: ${_date} - Running Late'
    variablesUnresolved: false
    vertexSelection: false
    vertices: []
    virtualResource: null
    virtualResourceVar: null
agent: ULM - SAP
agentCluster: SAP-Linux-agent
agentClusterVar: null
agentVar: null
avgRunTime: 8
avgRunTimeDisplay: 8 Seconds
broadcastCluster: null
broadcastClusterVar: null
chainDesc: null
chainId: null
commandGroup: Submit
commandOptions: null
cpDuration: null
cpDurationUnit: Minutes
credentials: LINUX_USER_CRED_ULM
credentialsVar: null
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
dataSource: null
defFile: null
definitionOrModel: USAP Definition File
definitionOrModelJobVar: USAP Definition File
dispAbapName: RBDAPP01
dispSapEventId: null
dispSapEventParm: null
dispVariant: STATUS
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
emailNotification: null
enforceVariables: false
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_sap
firstRun: 2023-05-23 17:39:13 +0200
holdResources: false
immediate: true
infoPackage: null
infoPackageJobName: null
infoSource: null
jobClass: null
jobId: null
jobLog: true
jobLogChild: null
jobName: null
jobStatus: null
jobSteps: []
lastRun: 2025-01-15 14:13:05 +0100
lastRunTime: 1
lastRunTimeDisplay: 1 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logId: null
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:30
lsEnabled: true
lsNthAmount: 5
lsTime: 00:00
lsType: Duration
maxChildDepth: null
maxRunTime: 27
maxRunTimeDisplay: 27 Seconds
minRunTime: 1
minRunTimeDisplay: 1 Seconds
name: SAP-FICO-T001-EXTRACT
notes: []
opswiseGroups:
- DUC
- end_user_self_service
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: OUTERR
outputType: STDOUT
overrideInstanceWait: 'No'
pcRestart: false
printAppLog: true
printAppRc: true
purge: false
purgeChild: null
repositoryOrFilesys: Script
requestId: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runCount: 422
runTime: 3188
runtimeDir: null
sapCmProfileId: null
sapCmProfileType: null
sapCmXmlFile: null
sapCommandMask: null
sapConnection: SAP-D44-CLIENT-001
sapConnectionVar: null
sapCred: SAP Demo user
sapCredVar: null
sapDispConfirmEvents: false
sapDispEventSelectState: New
sapDisplayCommand: Job Log
sapEventId: null
sapEventParm: null
sapFromDate: null
sapLang: null
sapPrinterName: null
sapToDate: null
sapView: Legacy View
script: scr_sap_script_Demo_simple
simulation: false
sourceSystem: null
spoolListRecipient: null
spoollist: true
spoollistChild: null
start: true
startHeld: false
startHeldReason: null
stepNum: null
summary: Extract SAP service Order extract
sysId: fcdb5becc67f49c6a58220c4f3b604ac
targetJobName: null
targetServer: null
targetVariantName: STATUS
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskSap
useAppRc: false
userEstimatedDuration: null
variables:
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: ABAP_NAME
  options: []
  sysId: 814419973a2f4794a267fbd6562c456c
  value: ZTABLE_EXT
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: ABAP_VARIANT
  options: []
  sysId: afe2848cfba84f4583c6bab699a51ac5
  value: ''
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: SAP_BATCH_USER
  options: []
  sysId: 5279c4a68bb64803aca5c0a08eff029a
  value: HOLGER
- allowEmptyOption: false
  allowUnlistedOption: false
  description: null
  name: sap_ext_file_name
  options: []
  sysId: acaa8bf120684020a93ed54a62901b3f
  value: C:\Users\ravi\sap_fico\T001_file.txt
version: 21
virtualResources:
- amount: 2
  resource: SAP-BACKGROUND-PROCESS-AVAILABILITY
  resourceVar: null
  sysId: 1b6f2da3a02840f7884abe4fb3636ad6
wait: true
waitChild: null
waitForOutput: false
