actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: null
agentCluster: AGENT_CLUSTER_APP_PROJECTA
agentClusterVar: null
agentVar: null
avgRunTime: 48
avgRunTimeDisplay: 48 Seconds
broadcastCluster: null
broadcastClusterVar: null
byPercentage: null
byScale: 1024
bySize: null
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_file_monitor
fileGroup: null
fileName: /podshare/${ops_agent_queue_name}_${file_name}
fileOwner: null
firstRun: 2023-06-19 17:31:41 +0200
fmtype: Changed
holdResources: false
lastRun: 2024-02-19 12:43:55 +0100
lastRunTime: 25
lastRunTimeDisplay: 25 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: true
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 08:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: true
lsNthAmount: 5
lsTime: 07:00
lsType: Time
maxFiles: null
maxRunTime: 678
maxRunTimeDisplay: 11 Minutes 18 Seconds
minFileScale: KB
minFileSize: null
minRunTime: 1
minRunTimeDisplay: 1 Seconds
name: OPEN-SHIFT-FILE-MONITOR
notes: []
opswiseGroups:
- App1
overrideInstanceWait: 'No'
recursive: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 29
runTime: 1383
scanForward: false
scanText: null
simulation: false
stableSeconds: null
startHeld: false
startHeldReason: null
summary: Check for billing input files in the Amsterdam Machine
sysId: 65cb2984299249e3ba22371d5f1f38c8
timeZonePref: -- System Default --
toScale: 1024
toSize: null
triggerOnCreate: false
triggerOnExist: false
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFileMonitor
useRegex: false
userEstimatedDuration: null
variables: []
version: 7
virtualResources: []
