actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
calculateCp: false
calendar: null
cpDuration: null
cpDurationUnit: Minutes
criticalEndpoints: []
customField1:
  label: Agency code
  value: null
customField2:
  label: Output Link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.8.0.0
exportTable: ops_task_workflow
firstRun: ''
holdResources: false
instanceWait: -- None --
lastRun: ''
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
name: RECURRING-FILE-PROCESS
notes: []
numberOfTasks: 2
opswiseGroups: []
overrideCalendar: false
overrideInstanceWait: 'No'
resPriority: 10
resPriorityVar: null
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 0
runCriteria: []
runTime: 0
simulation: false
skippedOption: Show Skipped
startHeld: false
startHeldReason: null
stepActions: []
stepConditions: []
summary: CSV Functions Example -TEST CHANGES1
sysId: 6e82a2b2fa234a10a6b071743a283298
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskWorkflow
userEstimatedDuration: null
variables: []
version: 6
virtualResources: []
workflowEdges:
- condition:
    value: Success
  points:
  - x: '690'
    y: '250'
  sourceId:
    taskName: GET-MATCHING-FILE-LIST
    value: '2'
  straightEdge: false
  targetId:
    taskName: PROCESS-EACH-MATCHING-FILES
    value: '3'
workflowVertices:
- alias: null
  conditionExpression: null
  task:
    value: GET-MATCHING-FILE-LIST
  vertexId: '2'
  vertexX: '440'
  vertexY: '220'
- alias: null
  conditionExpression: null
  task:
    value: PROCESS-EACH-MATCHING-FILES
  vertexId: '3'
  vertexX: '880'
  vertexY: '230'
