actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: Airflow
agentCluster: null
agentClusterVar: null
agentVar: null
avgRunTime: 0
avgRunTimeDisplay: 0 Seconds
broadcastCluster: null
broadcastClusterVar: null
command: ./wmrott_script.sh
commandOrScript: Command
cpDuration: null
cpDurationUnit: Minutes
credentials: wilhelm
credentialsVar: null
customField1:
  label: Custom Field 1
  value: null
customField2:
  label: Output Link
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
enforceVariables: false
environment: []
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exitCodeOutput: null
exitCodeProcessing: Success Exitcode Range
exitCodeText: null
exitCodes: '0'
exportReleaseLevel: 7.7.1.0
exportTable: ops_task_unix
firstRun: 2023-05-26 12:00:55 +0200
holdResources: false
lastRun: 2023-07-27 14:48:10 +0200
lastRunTime: 0
lastRunTimeDisplay: 0 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
lockVariables: false
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 0
maxRunTimeDisplay: 0 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: WMROTT-Test-Task
notes: []
opswiseGroups:
- App1
outputFailureOnly: false
outputReturnFile: null
outputReturnNline: '100'
outputReturnSline: '1'
outputReturnText: null
outputReturnType: NONE
outputType: STDOUT
overrideInstanceWait: 'No'
parameters: null
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
retryExitCodes: null
retryIndefinitely: false
retryInterval: 60
retryMaximum: 0
retrySuppressFailure: false
runAsSudo: false
runCount: 15
runTime: 0
runtimeDir: /home/wilhelm
script: null
simulation: false
startHeld: false
startHeldReason: null
summary: Test Task (simple)
sysId: 23a60d115c504615bb58b5ca2698fbdf
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskUnix
userEstimatedDuration: null
variables: []
version: 6
virtualResources: []
waitForOutput: false
